import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Care-xyz",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

export const metadata = {
  title: "Care.xyz",
  description: "Trusted Care Service Platform"
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body style={{ padding: "20px", fontFamily: "sans-serif" }}>
        <nav>
          <a href="/">Home</a> |{" "}
          <a href="/my-bookings">My Bookings</a> |{" "}
          <a href="/login">Login</a>
        </nav>
        <hr />
        {children}
      </body>
    </html>
  );
}